version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8005
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - ALLWED_HOSTS='pmdsdata12'
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=password
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
